
# This section was automatically generated by instdev.
alias list='ls -la|more'
alias ls='ls -la'
alias sqlplus-leo='sqlplus leo2/leo@DB'

# find text in source
alias findtext='find $LEOHOME -type f -print -o -name build -prune -o -name build \
 -prune -o -name dist -prune -o -name rmiservers -prune -o -name bin -prune -o -name \
 eclipseOut -prune -o -name content -prune -o -name libraries -prune -o -name sitetools \
 -prune -o -name test_data -prune | xargs grep -n $*'

alias findtextWithContent='find $LEOHOME -type f -print -o -name build -prune -o \
-name rmiservers -prune -o -name bin -prune -o -name eclipseOut -prune -o -name \
libraries -prune -o -name sitetools -prune -o -name test_data -prune | xargs grep -n $*'

# ssh
alias qabox="ssh tester@esv4-qa57.corp.linkedin.com"
alias reflex="ssh -i ~/.ssh/sethkey.pem ec2-user@reflex.ws"
alias uni="ssh mediadmin@university.linkedin.com"

# local web server
alias cdwww="cd /var/www/html"
alias apachelog="tail -f /var/log/httpd/error_log"

# video settings
alias launchnvidia="sudo /usr/bin/nvidia-settings"

# navigate to directories
alias cdquickdeploy="cd $QUICK_DEPLOY"
alias cdtop='cd $LEOHOME'
alias cdstatic="cd $LEOHOME/content/static"
alias cdtest="cd $LEOHOME/content/test/js"
alias cdjs="cd $LEOHOME/content/static/js"
alias cdcss="cd $LEOHOME/content/static/css"
alias cdemails="cd $LEOHOME/notifier/cmpt/resources/emails/en_US"
alias cdtheme='cd $LEOHOME/ui/chrome/jsp/theme'
alias cdreg='cd $LEOHOME/reg/impl/jsp'
alias cdcollege='cd $LEOHOME/college'
alias cdpeer='cd $LEOHOME/content/static/js/apps/peertracker'

# re-compiles this file after changes are made
alias c="source ~/.bash_profile && source ~/.bashrc && source ~/.bash_aliases"

# starts selenium
alias selenium="$LEOHOME/gui-tests/selenium/lib/setup/start_rc.sh"

# SVN
alias svnstatown="svin status | grep 'A\|M' | cut -b 9- | xargs svin owners"

# database aliases
alias dbload='ant -f $LEOHOME/database/leo/build.xml db.testdata.core.load \
db.testdata.core.jobs.load db.testdata.subscribers.load db.testdata.core.recommendations.load \
 db.testdata.core.ayn.load'
alias list-wars='ls -l $LEOHOME/dist/*/war'
alias dbunload='ant -f $LEOHOME/database/leo/build.xml db.testdata.core.ayn.unload \
db.testdata.core.recommendations.unload db.testdata.core.unload db.testdata.core.jobs.unload \
db.testdata.subscribers.unload'
alias dbreload='dbunload;dbload'
alias dbjload='ant -f $LEOHOME/database/leo/build.xml db.testdata.core.jobs.load'
alias dbjunload='ant -f $LEOHOME/database/leo/build.xml db.testdata.core.jobs.unload \
db.testdata.subscribers.unload'
alias dbcsload='ant -f $LEOHOME/database/leocs/build.xml db.testdata.core.load'
alias recreload='ant -f $LEOHOME/database/leo/build.xml db.testdata.core.recommendations.unload \
db.testdata.core.recommendations.load'
alias sqlplus1='rlwrap sqlplus'
alias sqlleo='rlwrap sqlplus leo2/leo@DB'
alias sqlstg='sqlplus leo2/leo@STG'
alias sqldwh='sqlplus dwh/dwh@DWH'
alias sqlcs='sqlplus custservice/custservice@DB'
alias devdb='ssh oracle@devdb'

alias svdiff='svn diff --diff-cmd ~/bin/svndiff_helper $*'

# reset
alias restartlocal='ant -f build.xml -Dno.full.build=true dist'
alias restartinbox='ant -f tools.xml comm-inbox-bps.undeploy comm-server.undeploy comm-dispatcher.undeploy inbox.undeploy comm-inbox-bps.deploy comm-server.deploy comm-dispatcher.deploy inbox.deploy'
alias fullstop='undeploy-leo; stop-tomcat; bestop; fullclean'
alias restartall='cd $LEOHOME && killall -9 java && fullclean && ant -f tools.xml ivy-clean-locks && ant -f tools.xml ivy-fullclean all.start && ant -f tools.xml tomcat.start scds.deploy uas.deploy leo.deploy nmp.deploy reg.deploy pal.deploy'
alias restartuas='ant -f $LEOHOME/tools.xml uas.undeploy uas.deploy'
alias restartreg='ant -f $LEOHOME/tools.xml -Dfrontend.host=g-linkedin.com reg.undeploy reg.deploy'
alias restartgrowth='ant -f $LEOHOME/tools.xml scds.undeploy scds.deploy leo.undeploy leo.deploy lite.undeploy lite.deploy nmp.undeploy nmp.deploy fetch.undeploy fetch.deploy reg.undeploy reg.deploy inbox.undeploy inbox.deploy uas.undeploy uas.deploy genie.undeploy genie.deploy redirect.undeploy redirect.deploy nabook.undeploy nahbook.deploy shortlink-frontend.undeploy shortlink-frontend.deploy'
alias restartcollege='ant -f $LEOHOME/tools.xml college.undeploy college.deploy'

# front end start
alias festart='ant -f tools.xml tomcat.start scds.deploy uas.deploy leo.deploy nmp.deploy reg.deploy'

# backend services
alias bestop='killall -9 java'
alias beclean='rm -Rf $LEOHOME/dist/backend-container $LEOHOME/dist/core-container $LEOHOME/dist/services-container $LEOHOME/dist/apps-container'
alias fullclean='ant -f $LEOHOME/build.xml fullclean'
alias fullstart='ant -f $LEOHOME/tools.xml all.start'
alias bestopsc='ant -f $LEOHOME/tools.xml services-container.stop'
alias bestopbc='ant -f $LEOHOME/tools.xml backend-container.stop'
alias debugbc='$LEOHOME/dist/backend-container/bin/./backend-containerctl.sh -d start'
alias debugsc='$LEOHOME/dist/services-container/bin/./services-containerctl.sh -d start'
alias changebcport='cp ~/Projs2/backend-container/master_conf.sh $LEOHOME/dist/backend-container/conf/master_conf.sh'
alias bestart-debug-sc='ant -f $LEOHOME/tools.xml services-container.start; bestopsc; bestopsc; debugsc'
alias bestart-debug-scbc='ant -f $LEOHOME/tools.xml backend-container.start services-container.start; bestopsc; bestopbc; bestopbc; changebcport; debugsc; debugbc'
alias bedeploy='bestart-debug-sc; ant -f $LEOHOME/tools.xml all.start'
alias bedeploy-fulldebug='bestart-debug-scbc; ant -f $LEOHOME/tools.xml all.start'
alias bedeploy-media='ant -k -f $LEOHOME/tools.xml mpr.undeploy mupld.undeploy mpr.deploy mupld.deploy'

alias belogs='tail -1000F $LEOHOME/dist/core-container/logs/core-container.log $LEOHOME/dist/backend-container/logs/backend-container.log $LEOHOME/dist/services-container/logs/services-container.log  $LEOHOME/dist/apps-container/logs/apps-container.log $LEOHOME/dist/backend-container/logs/backend-container.log $LEOHOME/dist/services-container/logs/services-container.log  $LEOHOME/dist/apps-container/logs/apps-container.log'

alias catbslog='cat $LEOHOME/dist/backend-container/logs/backend-container.log $LEOHOME/dist/services-container/logs/services-container.log $LEOHOME/dist/apps-container/logs/apps-container.log $LEOHOME/dist/core-container/logs/core-container.log $LEOHOME/dist/mailtester/logs/mailtester.log'
alias jsplog="tail -f $LEOHOME/dist/tomcat-container/logs/catalina.out | egrep '\[CompileAndLoad\]|\[DispatchController\]|\[JspCompileServletSpring\]|\[CoreServlet\]'"

alias leoallstartdb="dbdate && cd $LEOHOME && ant -f $LEOHOME/database/build.xml all.db.reinit all.db.testdata.reload && leoallstart"
alias dbdate="echo 'db login' && ssh root@10.254.254.2 \"date -s '\$(date)'\""
alias leoallstart="cd $LEOHOME && ant fullclean && leoallstartnoclean"
alias leoallstartnoclean="cd $LEOHOME && tomstart && ant -f tools.xml all-containers.start all.start mupld.deploy mpr.deploy && leostart && ant nmp.deploy inbox.deploy && ant -f tools.xml media-proxy.deploy nprofile.deploy"
alias leoallstartnocleandb="dbdate && cd $LEOHOME && ant -f $LEOHOME/database/build.xml all.db.reinit all.db.testdata.reload && cd $LEOHOME && tomstart && ant -f tools.xml all.start mupld.deploy mpr.deploy && leostart && ant nmp.deploy inbox.deploy && ant -f tools.xml media-proxy.deploy nprofile.deploy"
alias leostart="ant leo.deploy"  # make sure leo is undeployed first
alias leostop="ant -f $LEOHOME/build.xml leo.undeploy"
alias tomstart="cd $LEOHOME && ant -f tools.xml tomcat.start"
alias tomstop="ant -f $LEOHOME/tools.xml tomcat.stop"
alias tomlog="tail -f ~/src/network/dist/tomcat-container/logs/catalina.out"
alias vtomlog="vim ~/src/network/dist/tomcat-container/logs/catalina.out"
alias tlogs='tail -1000f $LEO_HOME/dist/*-container/logs/*-container.log'

# list services
alias frontier-list="egrep \"import.*frontier-.*-targets|import.*darwin-.*-targets\" */*war/build.xml* | awk '{print $1}' | awk -F / '{print $1\"-\"$2}'"

alias belogs-services='tail -1000F $LEOHOME/dist/services-container/logs/services-container.log $LEOHOME/dist/services2-container/logs/services2-container.log | grep -v PartitionedPeopleSearchService'
alias belogs-core='tail -1000F $LEOHOME/dist/core-container/logs/core-container.log'
alias belogs-backend='tail -1000F $LEOHOME/dist/backend-container/logs/backend-container.log'
alias belogs-apps='tail -1000F $LEOHOME/dist/apps-container/logs/apps-container.log'
alias belogs-contacts='tail -1000F /Volumes/SSD/linkedInSrc/network/dist/services-container/logs/anet_contacts.log'
alias palogs='find $LEOHOME/dist -name "*public*.log" |xargs tail -1000F'
alias tomcatlogs='tail -1000F $TOMCAT_HOME/logs/catalina.out'
alias dberrors='find $LEOHOME/database -name "*.log" |xargs grep -i "ERROR" | grep -v "No errors"'
alias beerrors='find $LEOHOME/dist -name "*.log" |xargs grep -i "error"'
alias taillogs='for f in `find . -iname "*.log"` ; do tail -f $f | sed -e "s/^/`basename $f`: /" & done'
alias killtails='kill -9 `ps -A | grep -v grep | grep tail | cut -c 1,2,3,4,5`'
alias db-reinit-all='ant -f $LEOHOME/database/build.xml all.db.reinit && ant -f $LEOHOME/database/media/build.xml db.reinit'
alias db-reinit-leo='ant -f $LEOHOME/database/leo/build.xml db.reinit'
alias db-reinit-anet='ant -f $LEOHOME/database/anet/build.xml db.reinit'
alias db-reinit-media='ant -f $LEOHOME/database/media/build.xml db.reinit'
alias db-testdata-all='ant -f $LEOHOME/database/build.xml all.db.testdata.reload'
alias db-testdata-leo='ant -f $LEOHOME/database/leo/build.xml db.testdata.core.reload'
alias db-testdata-leocs='ant -f $LEOHOME/database/leocs/build.xml db.testdata.core.reload'
alias db-testdata-news='ant -f $LEOHOME/database/news/build.xml db.testdata.all.reload db.testdata.core.keywords.reload db.testdata.topic.seed.unload db.testdata.topic.seed.load db.testdata.feed.unload db.testdata.feed.load'
alias db-testdata-groups='ant -f $LEOHOME/database/leo/build.xml db.testdata.managedgroup.unload; ant -f $LEOHOME/database/leo/build.xml db.testdata.managedgroup.load'
alias db-testdata-anet='ant -f $LEOHOME/database/anet/build.xml db.testdata.core.reload db.testdata.companyGroups.unload db.testdata.companyGroups.load db.testdata.groups.unload db.testdata.groups.load'
alias db-testdata-init='db-testdata-leo; db-testdata-anet; db-testdata-news'
alias ant.nfb='ant -Dno.full.build=true' 
alias start-tomcat='ant -f $LEOHOME/tools.xml tomcat.start -Dctl.script.args=-d'
alias stop-tomcat='ant -f $LEOHOME/tools.xml tomcat.stop'
alias undeploy-leo='ant -f $LEOHOME/tools.xml leo.undeploy'
alias deploy-leo='ant -f $LEOHOME/tools.xml -Dno.jsmin=1 leo.deploy'
alias deploy-leo-min='ant -f $LEOHOME/tools.xml -Dno.jsmin=1 -Dno.static=1 leo.deploy'
alias undeploy-leocs='cd $LEOHOME; ant leocs.undeploy'
alias deploy-leocs='ant -f $LEOHOME/tools.xml -Dno.jsmin=1 -Dno.static=1 leocs.deploy'
alias anet-bl-session='ant -f $LEOHOME/anet/bl-session/build.xml dist'
alias leo-gui-impl='ant -f $LEOHOME/leo/gui-impl/build.xml dist -Dno.full.build=1'
alias leo-bl-impl='ant -f $LEOHOME/leo/bl-impl/build.xml dist -Dno.full.build=1'
alias leo-bl-session='leo-bl-impl; leo-gui-impl'
alias reload-leo-only='ant -f $LEOHOME/build.xml leo.reload -Dno.full.build=1 -Dno.static=1'
alias reload-leo='anet-bl-session; leo-bl-session; reload-leo-only'
alias reload-leocs='ant -f $LEOHOME/leocs/bl-impl/build.xml dist -Dno.full.build=1; ant -f $LEOHOME/leocs/gui-impl/build.xml dist -Dno.full.build=1; ant -f $LEOHOME/build.xml leocs.reload -Dno.full.build=1 -Dno.static=1' 
alias anet-api='ant -f $LEOHOME/anet/api/build.xml'
alias reload-anet='ant -f $LEOHOME/anet/war/build.xml undeploy deploy'
alias reload-news-discovery='ant -f $LEOHOME/news/discovery-war/build.xml undeploy deploy'
alias reload-news-search='ant -f $LEOHOME/news/search-war/build.xml undeploy deploy'
alias i18nconvert='ant -f $LEOHOME/leo/gui-impl/build.xml i18nconvert -Dno.full.build=true'
alias portforward="~/linkedInSrc/sync-scripts/./portforward.sh"
alias devdb-portforward="ssh -N -l oracle devdb -L:1521:devdb:1521"
alias cpsyncscripts="cp ~/linkedInSrc/sync-scripts/sync* ."

# simulate actions
alias sendnudge='$LEOHOME/dist/nudge-bes-cmdline/bin/nudge-bes.sh -futureOffset 10m'
alias senddownshift='cd $LEOHOME/comm/egt-test && ant test -Dtests.to.run=test.egt.TestANetDigestDownshift:testHappyPath:testHappyPath'
alias senddownshift2='cd $LEOHOME/comm/egt-test && ant test -Dtests.to.run=test.egt.TestANetDigestDownshift:testHappyPath:testHappyPath -Dno.full.build=true'
alias send1bfirst='cd $LEOHOME && ant -f comm/egt-test/build.xml -Dtests.to.run=test.egt.TestNetworkUpdatesServiceMessage:testMessageInTestCaseF test'
alias send1b='cd $LEOHOME && ant -f comm/egt-test/build.xml -Dno.full.build=true -Dtests.to.run=test.egt.TestNetworkUpdatesServiceMessage:testMessageInTestCaseF test'
alias sendpulse='cd $LEOHOME/comm/egt-test && ant -Demail.id=200 -Dno.full.build=true'

alias publishsvsfirst='cd $LEOHOME/snapshot/bes-cmdline && ant'
alias publishsvs='cd $LEOHOME/dist/snapshot-bes-cmdline/bin && ./snapshot-bes.sh -futureOffset 1d30m'

alias list-deployed='find $LEOHOME/dist -name *container.log | xargs grep deployed'

alias slt='open -a "Sublime Text 2"'

# QuickDeploy
alias qdupdate='svn update $QUICK_DEPLOY'
alias qdstart='$QUICK_DEPLOY/qd.sh start'
alias qdrestart='$QUICK_DEPLOY/qd.sh restart'
alias qdstop='$QUICK_DEPLOY/qd.sh stop'
#alias qdstop='$QUICK_DEPLOY/qdtunnels.sh stop && $QUICK_DEPLOY/stop-proxy.sh'
#alias qdstart='$QUICK_DEPLOY/start-proxy.sh && $QUICK_DEPLOY/qdtunnels.sh start'

# utils
alias tmux=tmux -2

# VNC
alias runvnc='sudo service vncserver start'
alias newvnc='vncserver :6 -geometry 1440x900 -depth 16'

# kafka
alias zookeeper-start='cd ~/dev/sensei-1.0.0 && ./bin/zookeeper-server-start.sh resources/zookeeper.properties &'
alias kafka-start='cd ~/dev/kafka && ./bin/kafka-server-start.sh config/server.properties &';
alias kafka-run='zookeper-start kafka-start'
alias kafka-test-producer='cd ~/dev/kafka && ./bin/kafka-producer-shell.sh --server kafka://localhost:9092 --topic intouch'
alias kafka-test-consumer='cd ~/dev/kafka && ./bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic intouch'
alias kafka-consumer='$INTOUCH_HOME/kafka/current-version/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic $0 --from-beginning'
# git 
alias git-pull='/home/smclaugh/src/college.git/fetch_merge.sh'

function kcon() { $INTOUCH_HOME/kafka/current-version/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic "$@" --from-beginning ;}

#js test driver
alias jstest-start='java -jar $JSTESTDRIVER_HOME/JsTestDriver-1.3.4-a.jar --port 4224'
alias jstest-start-dev='java -jar /home/smclaugh/dev/js-test-driver/trunk/JsTestDriver/target/bin/JsTestDriver.jar --port=2013'
alias jstest-run='java -jar $JSTESTDRIVER_HOME/JsTestDriver-1.3.4-a.jar --tests all'
alias jstest-run-dev='java -jar /home/smclaugh/dev/js-test-driver/trunk/JsTestDriver/target/bin/JsTestDriver.jar --tests all'
alias test-status='curl eat1-qa141.corp.linkedin.com:2011/connections'
alias cdjstd='cd /home/smclaugh/dev/js-test-driver/trunk/JsTestDriver'

# resolution
alias r1280='xrandr -s 1280x800'
alias r1440='xrandr -s 1440x900'

# eclipse
alias eclipy='/home/smclaugh/tools/eclipse/eclipse &'
alias kl='kill -9 %3'

# selenium
alias testff8='/home/smclaugh/src/my-trunk.git/trunk/gui-tests/selenium/lib/setup/start_rc_ff8.sh'

# browser death!
alias bdeath='killall -9 firefox && killall -9 chrome'

# synergy
alias syn='synergys -f --name smclaugh-ld -c /home/smclaugh/synergy.conf'

# git
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"

# fizzy
alias fizlog='tail -f /var/log/trafficserver/fizzyserver.log'
